dist: trusty
language: go
go: '1.13.x'
install: make setup
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: ./goreleaser
    on:
      tags: true
notifications:
  email: false
